import {
  ShieldAlert,
  Users,
  Layers,
  Building2,
  CheckCircle2,
  Activity,
  History,
} from "lucide-react";

export const AdminDashboardPage: React.FC = () => {
  const stats = [
    {
      label: "Total Users",
      val: "480 Accounts",
      sub: "420 Students, 42 Recruiters",
      icon: Users,
      color: "text-amber-400",
    },
    {
      label: "Active Skills in Taxonomy",
      val: "24 Skills",
      sub: "6 Categories mapped",
      icon: Layers,
      color: "text-sky-400",
    },
    {
      label: "Verified Enterprises",
      val: "18 Companies",
      sub: "4 Pending review",
      icon: Building2,
      color: "text-indigo-400",
    },
    {
      label: "System Health",
      val: "99.9% Uptime",
      sub: "PostgreSQL + Express",
      icon: Activity,
      color: "text-emerald-400",
    },
  ];

  const recentAudits = [
    {
      action: "CREATE_USER",
      user: "alex.student@skillbridge.dev",
      role: "STUDENT",
      time: "10 mins ago",
      status: "SUCCESS",
    },
    {
      action: "POST_OPPORTUNITY",
      user: "recruiter@techcorp.io",
      role: "INDUSTRY",
      time: "45 mins ago",
      status: "SUCCESS",
    },
    {
      action: "SUBMIT_ASSESSMENT",
      user: "alex.student@skillbridge.dev",
      role: "STUDENT",
      time: "1 hour ago",
      status: "SUCCESS",
    },
    {
      action: "REFRESH_TOKEN",
      user: "admin@apexuniversity.edu",
      role: "INSTITUTION_ADMIN",
      time: "2 hours ago",
      status: "SUCCESS",
    },
  ];

  return (
    <div className="space-y-8 max-w-7xl mx-auto">
      {/* Banner */}
      <div className="glass-panel p-6 sm:p-8 rounded-3xl border border-slate-800 bg-gradient-to-r from-slate-900 via-[#1f1a10] to-slate-900 flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
        <div className="space-y-2">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-amber-500/10 border border-amber-500/20 text-amber-300 text-xs font-semibold">
            <ShieldAlert className="w-3.5 h-3.5 text-amber-400" />
            <span>Platform Master Administration</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-white">
            Root Administrative Console
          </h1>
          <p className="text-sm text-slate-400 max-w-2xl leading-relaxed">
            Monitor system-wide platform metrics, verify new corporate and
            collegiate registrations, maintain the global skill taxonomy, and
            audit platform activity.
          </p>
        </div>

        <div className="px-4 py-2 rounded-xl bg-slate-900 border border-slate-800 text-xs font-mono text-amber-400">
          Role: SUPER_ADMIN
        </div>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-6">
        {stats.map((stat, idx) => {
          const Icon = stat.icon;
          return (
            <div
              key={idx}
              className="glass-panel p-5 rounded-2xl border border-slate-800 flex items-center space-x-4"
            >
              <div className="w-12 h-12 rounded-xl bg-slate-900 border border-slate-800 flex items-center justify-center shrink-0">
                <Icon className={`w-6 h-6 ${stat.color}`} />
              </div>
              <div>
                <p className="text-xs text-slate-400 font-medium">
                  {stat.label}
                </p>
                <h3 className="text-xl font-extrabold text-white tracking-tight">
                  {stat.val}
                </h3>
                <span className="text-[11px] text-slate-400 font-mono">
                  {stat.sub}
                </span>
              </div>
            </div>
          );
        })}
      </div>

      {/* Audit Log Preview */}
      <div className="glass-panel p-6 sm:p-8 rounded-3xl border border-slate-800 space-y-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="p-2 rounded-xl bg-slate-900 border border-slate-800 text-amber-400">
              <History className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-white">
                Live Platform Audit Stream
              </h3>
              <p className="text-xs text-slate-400">
                Security audit log records generated by the backend engine
              </p>
            </div>
          </div>
          <span className="px-3 py-1 rounded-full bg-slate-900 border border-slate-800 text-[11px] font-mono text-emerald-400 flex items-center gap-1.5">
            <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse"></span>
            Real-Time
          </span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead>
              <tr className="border-b border-slate-800 text-slate-400">
                <th className="pb-3 font-semibold">Action</th>
                <th className="pb-3 font-semibold">Initiator</th>
                <th className="pb-3 font-semibold">Role</th>
                <th className="pb-3 font-semibold">Time</th>
                <th className="pb-3 font-semibold">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-850">
              {recentAudits.map((item, idx) => (
                <tr
                  key={idx}
                  className="hover:bg-slate-900/40 transition-colors"
                >
                  <td className="py-3.5 font-mono font-semibold text-amber-400">
                    {item.action}
                  </td>
                  <td className="py-3.5 text-white font-medium">{item.user}</td>
                  <td className="py-3.5">
                    <span className="px-2 py-0.5 rounded-full bg-slate-850 text-slate-300 text-[10px] font-mono">
                      {item.role}
                    </span>
                  </td>
                  <td className="py-3.5 text-slate-400 font-mono">
                    {item.time}
                  </td>
                  <td className="py-3.5">
                    <span className="text-emerald-400 font-bold flex items-center gap-1">
                      <CheckCircle2 className="w-3.5 h-3.5" />
                      <span>{item.status}</span>
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
